### PR TITLE
draft of both panels for example figure

### PR DESCRIPTION
**Pull request by gottacatchenall**
here's a draft with both panels and some not great looking plots. is this what we want in this figure and then other plots (AUC, network embedding) go with their associated section later in the text?@tpoisot @TanyaS08 

example_concept_both_panels

### CODE REVIEW

**Comment by TanyaS08** [comment]
Okay to start I like the 1:1 match and the symbology marries well with the conceptual figure - I do wonder though if it doesn't make sense for the reader to have seen the conceptual figure first though?? But I think it might be a case of seeing if this flies/how it reads and _maybe_ reconsidering a  small re-shuffle?? Cutting the rambling short - I'd say lets see how it pans out in the current structure but keeping the (potential, perceived and probably imagined) issue in mind

**Comment by TanyaS08** [comment]
I'm actually torn - I think the conceptual figure fits better 'near' the nitty gritty parts of the ms and introducing it too soon might not be conducive either and in a way it makes sense we get the 'housework' out of the way i.e. the problems and solutions.

**Comment by gottacatchenall** [comment]
now adding tim's figure as the second panel gives 
example_concept_both_panels

thoughts? @tpoisot  @TanyaS08

**Comment by tpoisot** [comment]
it's going to be a big figure

**Comment by tpoisot** [comment]
what about adding letters and referring to them explicitly? - the empirical network is A, the latent traits are B, the training is C, validation is D, and imputed networks E?

**Comment by tpoisot** [comment]
that being said - this is something we can work into the text later, so let's maybe have a readthrough to see if there are big red flag issues, and if not we can ask everyone _including AG + DG_ to read it?

**Comment by tpoisot** [comment]
and we give everyone a little deadline for comments that is one day before our next meeting, so we can incorporate feedback and have a preprintable-ish version?

**Comment by gottacatchenall** [comment]
i think this plan is good, based on the changes listed in #89 the only things i feel strongly about changing prior to sending out are
1. shifting the list of databases to a table
2. introduction summarizes new structure of paper  
3. a conclusion

which should all be quick. should we merge this and go from there?

**Comment by tpoisot** [comment]
I was going to suggest we close this one, and see what changes to make to the figure based on feedback. I'll leave a tentative game plan in #89

**Pull request closed without merging**
