### PR TITLE
Box with biological examples

### PR DESCRIPTION
**Pull request by DominiqueCaron**
#1

### CODE REVIEW

**Comment by DominiqueCaron** [comment]
First draft of the box ready for review. I kept it very concise. I think that if I choose to go into more detail, it can rapidly grow into a huge box. I can expand more, but I'll wait until we decided which journal and article format we are doing.

Also, maybe (Laura's idea) we could add a figure. It would be a great opportunity to put some cute plants, pollinators and viruses and make the paper a little more inviting for less-quantitative ecology folks.

**Comment by TanyaS08** [comment]
I am 100% behind cute illustrations - always! But I do think it a good idea and makes the ms more welcoming

**Review by TanyaS08 — COMMENTED** [review]
I like that the two examples come from different 'fields' but are not too niche either :) I'm not sure how we envision 'creating' the box - maybe @tpoisot has some ideas/a tricks up his sleeve as to how we would go about doing this. Also just to reiterate - 100% down for some illustrations as well and something I'm down to brainstorm at some point

**Review by tpoisot — APPROVED** [review]
I think we can merge this and refine the text on friday

**Review by TanyaS08 — DISMISSED** [review]

**Review by TanyaS08 — APPROVED** [review]

**Review by gottacatchenall — APPROVED** [review]

**Pull request closed without merging**
