### PR TITLE
Co-author feedback edits

### PR DESCRIPTION
**Pull request by TanyaS08**
Started working through suggested edits

### CODE REVIEW

**Comment by TanyaS08** [comment]
- [ ] **l. 109** "I find it confusing how co-occurrence and interactions are mixed.The first half of the sentence seems to indicate that C is built with interactions, while the second half seems to indicate that it is built with co-occurrence.

If C is built with interactions, maybe we should name it adjacency matrix A ?"

**Comment by tpoisot** [comment]
I very much vibe with l 893

**Comment by gottacatchenall** [comment]
>  l. 121 Maybe add the proportions? I think it was 20 testing - 80 training

related to #143

**Comment by gottacatchenall** [comment]
> **l. 697** Indirect interactions---either higher-order interactions between species, _or interaction strengths that themselves interact_ <- more clarity re interaction strengths interacting?

this is to say that A_ij = f(A_ik, A_jk)

**Comment by gottacatchenall** [comment]
> l. 616 Again, this sentence does not make sense. Abundances is used in neutral models. Also it is written the effect of X would have no effect.

this sentence should read:

A neutral approach would assume the probability of an interaction is only function of abundance and traits would have no effect (Poisot, Stouffer, and Gravel 2015; Pichler et al. 2020).

**Comment by TanyaS08** [comment]
> I very much vibe with l 893

Samesies

**Comment by TanyaS08** [comment]
> > **l. 697** Indirect interactions---either higher-order interactions between species, _or interaction strengths that themselves interact_ <- more clarity re interaction strengths interacting?
> 
> this is to say that A_ij = f(A_ik, A_jk)

I think its okay as it currently stands in the doc

**Comment by TanyaS08** [comment]
> * **l. 109** "I find it confusing how co-occurrence and interactions are mixed.The first half of the sentence seems to indicate that C is built with interactions, while the second half seems to indicate that it is built with co-occurrence. - If C is built with interactions, maybe we should name it adjacency matrix A ?" (Dom C also pointed out we use C later in the doc to refer to connectence and this would also address the qualm - TS 🐾 )

We first aggregate all ~~Interactions~~ species into a co-occurrence matrix $A$ which
represents whether a given pair of species $(i,j)$ was observed coexisting
across any location.

That makes sense right? also I've taken the liberty of calling this matrix A since we have the conflict with C elsewhere and we don't refer to the co-occurrence matrix elsewhere in the text/figure so that should be okay...

**Comment by TanyaS08** [comment]
> * [x]  **l. 111**  If we are talking about coexistance and not interaction, Dunne 2006 is not really relevant
> * [x]  **l. 121** Maybe add the proportions? I think it was 20 testing - 80 training

Removed Dunne since it is more food web specific and added the 80/20 split

**Comment by gottacatchenall** [comment]
> We first aggregate all ~Interactions~ species into a co-occurrence matrix $A$ which
> represents whether a given pair of species $(i,j)$ was observed coexisting
> across any location.
> 
> That makes sense right? also I've taken the liberty of calling this matrix A since we have the conflict with C elsewhere and we don't refer to the co-occurrence matrix elsewhere in the text/figure so that should be okay...

i think Aij =1 if i and j were interacting across any site, but to clarify the language we probably need to ask @tpoisot

**Comment by tpoisot** [comment]
I'll have a look tomorrow. A is usually an adjacency matrix, so maybe we just need to reword in a way that is more like " we represent these interactions by the adjacency matrix of the network they form" or something

**Comment by gottacatchenall** [comment]
think we can merge this to give it a read and make a new issue for the coocc matrix sentence change?

**Review by gottacatchenall — APPROVED** [review]

**Comment by TanyaS08** [comment]
I want to say yes... Not sure if @tpoisot needs/wants a 'clean' `master` though _i.e._ sans this last flurry of edits??

**Comment by tpoisot** [comment]
I vote you merge this, and I'll have a read this afternoon, submit later today

**Pull request merged**
