### PR TITLE
How do we predict what the species pool at a particular location is? 

### PR DESCRIPTION
**Pull request by gabrieldansereau**

### CODE REVIEW

**Comment by gabrieldansereau** [comment]
I've tried to describe how predicting the species pool needs to be integrated into our predictive framework for networks and interactions, but I'm not sure how to get there. I've mostly listed methods deriving from SDMs, as it's the way I see it, but maybe we want to go somewhere else?

Also, looking at the conceptual and the everything-is-connected figures just now, I find I might have been going in a different direction here. I wrote about improving species pool predictions from SDMs using network properties and interactions, whereas the figures are more about the species pool altering networks in space. Is that in contradiction?

**Comment by TanyaS08** [comment]
> I've tried to describe how predicting the species pool needs to be integrated into our predictive framework for networks and interactions, but I'm not sure how to get there. I've mostly listed methods deriving from SDMs, as it's the way I see it, but maybe we want to go somewhere else?
> 
> Also, looking at the conceptual and the everything-is-connected figures just now, I find I might have been going in a different direction here. I wrote about improving species pool predictions from SDMs using network properties and interactions, whereas the figures are more about the species pool altering networks in space. Is that in contradiction?

Just chipping in here regarding the everything is connected figure specifically - Linking network structure and spp. pool is more of an omission on my side and not a contradiction I would argue. My focus was more on the abiotic conditions as opposed to space per se and it would be cool to get your input to develop those links in the figure in more detail a bit further down the line!

**Comment by gottacatchenall** [comment]
^ agreed

**Review by tpoisot — APPROVED** [review]

**Comment by tpoisot** [comment]
I think the section works as it is, especially because the message is "SDM and networks people must talk". This is going to be some more arguments for what @gottacatchenall is cooking in the "unique data representation" paper. I vote this can be merged into the integration branch.

**Review by TanyaS08 — APPROVED** [review]

**Pull request merged**
