### PR TITLE
What are the most important measures to predict?

### PR DESCRIPTION
**Pull request by tpoisot**

### CODE REVIEW

**Comment by tpoisot** [comment]
@Norma-Forero I've made a first draft of this answer, your turn!

**Comment by tpoisot** [comment]
@Norma-Forero and I are happy to announce this one is ready for review before merging to the temporary branch

**Review by TanyaS08 — COMMENTED** [review]
As a suggestion could we not maybe retool the question again and have it reflect that conductance is the most important property to predict right off the bat? So maybe 'Why is conductance the most important network property to predict?' That being said not opposed to the current version

**Comment by tpoisot** [comment]
@TanysS08 I see your point, but I think it's a better idea to keep the question as is -- this way, we bring a good news (there's only one thing that's really really important), instead of the question being purely rethorical.

**Review by gabrieldansereau — APPROVED** [review]
I like it -- it's great for someone like me who doesn't know much about network properties. It summarizes well why connectance is important and how it can be derived, while leaving the specifics to the relevant papers. It's exactly what I'd expect in this section.

**Review by DominiqueCaron — APPROVED** [review]
Looks good to me!

**Review by TanyaS08 — APPROVED** [review]

**Pull request merged**
