### PR TITLE
Feedback from co-authors - edits

### PR DESCRIPTION
**Pull request by TanyaS08**
This is probably pre-emptive depending on what we decide to do in #108 but I've gone through and changed the _minor_ corrections - i.e. avoiding anything that has a `RED FLAG` and tagged them as resolved. @gottacatchenall I think most of the RED FLAGs can probably be worked through independently as well but we can always save those that are 'big' for next weeks meeting

### CODE REVIEW

**Comment by tpoisot** [comment]
@TanyaS08 rebase to get the new structure and then we'll update

**Comment by TanyaS08** [comment]
Rebased with minimal tears - we're still keeping this open for edits right?

**Comment by gottacatchenall** [comment]
going to repost my question from #108 here:

should the conceptual figure not have numbered labels then? @tpoisot @TanyaS08 

also in #108  i moved some of the question around within each section to correspond with the order in the conceptual figure, which we might want to revert to how it was?`

**Comment by gottacatchenall** [comment]
yeah i think we should keep this open for now

**Comment by TanyaS08** [comment]
1) no numbers - heading numbers might not correspond with the figure at the end of it all. 

2) I haven't looked at the slight re-shuffle quite yet but I'll get on that

**Comment by gottacatchenall** [comment]
okay cool, i'm cleaning up the conceptual figure and removing numbers

**Pull request merged**
