### PR TITLE
What is interaction strength?

### PR DESCRIPTION
**Pull request by BenMerSci**
Just opened the branch.

### CODE REVIEW

**Comment by tpoisot** [comment]
A couple refs:

- https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210x.2012.00249.x
- https://www.jstor.org/stable/3505669

**Comment by BenMerSci** [comment]
@tpoisot @TanyaS08 @gottacatchenall, requested review because i'm a bit stuck. I'm still thinking of ways to improve this, but a the time it feels to me more like a list than a fluid connections of ideas.. If you have any suggestions on which things to go more in depth in or anything, feel free to mention it to me!

**Comment by BenMerSci** [comment]
@TanyaS08 @tpoisot @gottacatchenall I would say it is ready for review.

**Review by TanyaS08 — COMMENTED** [review]
I like where this is at :)

I've gone in and tweaked the final paragraph as little bit (nothing major though, mostly a bit on the flow side of things) and feel free to passionately reject them! I do like it though as it kind of sets up the next section.

One question/query though (and I really don't know if this is a thing) but can we talk about the idea that interactions can take on either positive/negative values as well (coming from a very pairwise interaction mindset here)?? But I guess its challenging since we can look at interaction strength in two ways either at the level of the individual (i.e. positive or negative for them) and then there is the bigger network structure linked to energy/biomass exchange and ecosystem functioning. Not sure if that is actually point that we could also bring up??

But these are maybe point to think about in the integration phase??

Okay I think thats enough musing...

**Review by tpoisot — APPROVED** [review]

**Review by TanyaS08 — APPROVED** [review]

**Pull request merged**
