### PR TITLE
How do we fit a predictive model?

### PR DESCRIPTION
**Pull request by gabrieldansereau**

### CODE REVIEW

**Comment by gabrieldansereau** [comment]
@tpoisot @gottacatchenall  (and anyone interested of course)
Do we want this to be on how to fit a model in general, as could be found in ML textbooks, or do we want to make it specific to fitting a model about networks?
Right now it feels like an unsatisfying hybrid with some studies name-dropping in the end

Also, I'm not sure where to stop describing the "fitting" part: to me fitting includes preparation, training, and tuning, but that requires some form of validation, which is described in the next question

**Comment by TanyaS08** [comment]
> @tpoisot @gottacatchenall (and anyone interested of course)
> Do we want this to be on how to fit a model in general, as could be found in ML textbooks, or do we want to make it specific to fitting a model about networks?
> Right now it feels like an unsatisfying hybrid with some studies name-dropping in the end

I think given that our target audience is quite broad it does make sense to come in from a more general angle before dropping into networks specifically. As iOS I think is a good starting base for the draft and we can always prune and expand where needed.

> Also, I'm not sure where to stop describing the "fitting" part: to me fitting includes preparation, training, and tuning, but that requires some form of validation, which is described in the next question

Yeah agreed this and the next section do need to be able to 'talk' to each other - something that is probably a post-integration task!

**Review by TanyaS08 — APPROVED** [review]
Coming in as a 3rd party but I think this is good to go for integration

**Review by gottacatchenall — APPROVED** [review]
:+1:

**Pull request merged**
