### PR TITLE
Misc/assets

### PR DESCRIPTION
**Pull request by tpoisot**

### CODE REVIEW

**Comment by tpoisot** [comment]
This should make the website + PDF work

**Comment by tpoisot** [comment]
I'm also going to manually merge this into the _INTEGRATION_ PRs to make sure we can see the results there.

**Comment by tpoisot** [comment]
Done, all five integration branches should build now.

**Review by gottacatchenall — APPROVED** [review]
:+1:

**Review by TanyaS08 — APPROVED** [review]

**Pull request merged**
