### PR TITLE
Restructure 

### PR DESCRIPTION
**Pull request by gottacatchenall**

### CODE REVIEW

**Comment by gottacatchenall** [comment]
here's a draft of the conceptual panel for the example, and below would be the plots with actual data.
example_concept_panel

 is this what you were thinking @tpoisot?

**Comment by gottacatchenall** [comment]
1. Introduction
- What is a species interaction network?
- Why should we predict species interaction networks?
- Who would benefit from better prediction of species interaction networks?

2. A Case Study in Network Prediction
- _Case Study Figure_ (top row conceptual representation of ML example, bottom row actual data)
- Tim's Stuff  

3. A Roadmap Toward Prediction of Species Interaction Networks across Space and Time
- What is currently limiting our understanding of species interaction networks?
- What is the path forward toward understanding species interaction networks?
- _Conceptual Figure_

4. A Primer on Prediction of Species Interaction Networks
- Models
    - What is a predictive model? 
    - What do you need to build a predictive model?
    - How do we validate a predictive model?
- Networks and Interactions
    - How do we predict how species that have never co-occurred will interact?
    - Why predict networks and interactions at the same time?
    - What is the most important property of a network to predict?
    - How are interaction strengths inferred?
    - What about indirect and higher-order interactions?
    - How do we determine what interaction networks are feasible?
- Space
   - How much do networks vary over space?
   - How do we predict what the species pool at a particular location is?
   - What is the spatial scale suitable for the prediction of species interactions?
- Time
   - Why should we forecast species interaction networks?
   - How do we turn a predictive model into a forecasting model?
   - How can we validate a forecasting model?

Conclusion

**Comment by tpoisot** [comment]
oof I hadn't seen this one and I made a few changes to the overall structure

**Comment by tpoisot** [comment]
the most relevant change I made was removing the "What is a network?" section and merging it into "Why predict"

**Comment by gottacatchenall** [comment]
i think it makes sense as is tho :call_me_hand:

**Pull request merged**
