### PR TITLE
How could predictions for individual species, such as those used by IPBES/IUCN, be improved by considering ecological interactions?

### PR DESCRIPTION
**Pull request by gabrieldansereau**

### CODE REVIEW

**Comment by gabrieldansereau** [comment]
I'm torn between 2 directions here: should this focus on how -- concretely, mechanistically -- interactions improve single-species  models (I'm thinking SDMs, but it could be other ones too), or should it focus on how interactions fit into IUCN, IPBES, and generally conservation predictions?

I think I might I have strayed too far towards the 2nd one. And maybe it's not focusing enough on _how_ interactions improve things, and too much on _yes_ interactions _will_ improve things

**Comment by TanyaS08** [comment]
> I'm torn between 2 directions here: should this focus on how -- concretely, mechanistically -- interactions improve single-species models (I'm thinking SDMs, but it could be other ones too), or should it focus on how interactions fit into IUCN, IPBES, and generally conservation predictions?
> 
> I think I might I have strayed too far towards the 2nd one. And maybe it's not focusing enough on _how_ interactions improve things, and too much on _yes_ interactions _will_ improve things
> 
> Also interactions improving single-species predictions really ties in with what I discussed on SDMs in the species pool question #23, and I'm not sure how to treat those separately

I think because the section before this question is the one about improving SDMs so the reader is already primed/understands the value of interactions and I think it makes sense here to focus more on the 'user experience' side of things.

**Review by TanyaS08 — APPROVED** [review]
I think this works? 👾

**Review by gottacatchenall — APPROVED** [review]
:+1:

**Pull request merged**
