### PR TITLE
Update build system assets

### LINKED ISSUE #7: Update assets for the webpage rendering

### PR DESCRIPTION
**Pull request by tpoisot**
Closes #7 - this will generate the website, preprint, and line-edit PDFs

### CODE REVIEW

**Review by gottacatchenall — COMMENTED** [review]
looks good, although i'm curious if there is a way to test the github build workflow on this branch before merging :leopard: :leopard:

**Comment by tpoisot** [comment]
> looks good, although i'm curious if there is a way to test the github build workflow on this branch before merging

very good point - yes there is, let me write this up this way

**Comment by tpoisot** [comment]
This should be good - everything will get built within a PR, but only deploy after a push on master

**Review by gottacatchenall — APPROVED** [review]
:robot: :heavy_check_mark:

**Review by TanyaS08 — APPROVED** [review]
Most of this goes over my head - but it seems the code checks out 🦄

**Review by gottacatchenall — APPROVED** [review]

**Comment by gottacatchenall** [comment]
@tpoisot after merging it still looks like the build gets hung up on [the build copyedit pdf](https://github.com/PoisotLab/ms_network_prediction/actions/runs/340386099) stage. should we fix this is a new PR?

**Comment by tpoisot** [comment]
Well, it's because of something on the forecast figure, which had the same issue - I can have a look at what you did there and see how to fix it.

**Comment by tpoisot** [comment]
Strange, this seems to be something with the title, but it doesn't break on the template project - let me debut this today or so.

**Pull request merged**
