### PR TITLE
Conceptual Figure

### PR DESCRIPTION
**Pull request by gottacatchenall**

### CODE REVIEW

**Review by tpoisot — CHANGES_REQUESTED** [review]
I love it - can you make it on a white background?

**Comment by gottacatchenall** [comment]
around the outside of the whole thing or a white bg for each panel?

**Comment by tpoisot** [comment]
At the risk of frustrating your artistic aspirations, I'd go for something more subdued - keep the color for the content of the very small boxes, but the "structure" can be levels of (light) grey.

**Comment by gottacatchenall** [comment]
goin' corporate or something like that

**Review by tpoisot — APPROVED** [review]

**Review by TanyaS08 — APPROVED** [review]
I (grudgingly - and don't ask me why) have to agree that the light mode is pretty great...

**Comment by TanyaS08** [comment]
@tpoisot and @gottacatchenall we good to merge this to `master`?

**Pull request merged**
